- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - core
- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  apt:
    name: [ "lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - neovim
    - core
- name: Install fzf
  apt:
    name: fzf
    state: present
  tags:
    - install
    - fzf
- name: Install tmux
  apt:
    name: tmux
    state: present
  tags:
    - install
    - tmux
