- name: Install packages
  community.general.pacman:
    name: unzip
    state: present
  when:
    - ansible_facts['distribution'] == "Archlinux"
- name: Install packages (UBUNTU)
  apt:
    name: unzip
    state: present
  when:
    - ansible_facts['distribution'] == "Ubuntu"
- name: Create .ssh if not exists
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: '0755'
- name: Copy SSH Keys
  ansible.builtin.copy:
    src: .ssh/id_rsa
    dest: "~/.ssh/id_rsa"
    owner: root
    group: root
    decrypt: 'yes'
  tags:
    - ssh
