- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - core
- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  apt:
    name: [ "lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - neovim
    - core
- name: Install packages productivity
  apt: name={{item}}
  with_items:
    - tmux
    - fzf
  tags:
    - install
    - productivity
- name: Install gitkraken
  apt:
    deb: https://release.gitkraken.com/linux/gitkraken-amd64.deb
  tags:
    - install
    - gitkraken