- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - core
- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  apt:
    name: [ "lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - neovim
    - core
- name: Install fzf
  apt:
    name: fzf
    state: present
  tags:
    - install
    - fzf
- name: Install tmux
  apt:
    name: tmux
    state: present
  tags:
    - install
    - tmux
- name: Install lazydocker
  shell: curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
  tags:
    - install
    - lazydocker
- name: Install gitkraken
  apt:
    deb: https://release.gitkraken.com/linux/gitkraken-amd64.deb
  tags:
    - install
    - gitkraken
- name: Install lazygit step1
  shell: add-apt-repository ppa:lazygit-team/release && apt-get update
  tags:
    - install
    - lazygit
- name: Install lazygit step2
  apt:
    name: lazygit
    state: present
  tags:
    - install
    - lazygit
- name: Install nnn
  apt:
    name: nnn
    state: present
  tags:
    - install
    - nnn
- name: Intall obsidian
  apt:
    deb: https://github.com/obsidianmd/obsidian-releases/releases/download/v0.12.15/obsidian_0.12.15_amd64.deb
  tags:
    - install
    - obsidian
