- name: Install packages
  community.general.pacman:
    name: unzip
    state: present
- name: Copy SSH Keys
  ansible.builtin.copy:
    src: .ssh/id_rsa
    dest: "/home/{{ ansible_env.username }}/.ssh/id_rsa"
    owner: root
    group: root
    decrypt: 'yes'
  tags:
    - ssh
