- name: Install stow
  apt: 
    name: stow
    state: present
  tags:
    - install
    - dotfiles
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:LHernZ/.dotfiles.git'
    dest: "/home/$USER/.dotfiles"
    update: yes
    key_file: "/home/$USER/.ssh/id_rsa"
    accept_hostkey: yes
    version: main
  tags: 
    - install
    - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./manjaro
  tags:
    - install
    - dotfiles

