- name: Install nodejs and npm
  community.general.pacman:
    name: ["nodejs", "npm"]
    state: present
  when:
    - ansible_facts['distribution'] == "Archlinux"
  tags:
    - install
    - node
- name: Install nodejs and npm (UBUNTU)
  apt:
    pkg:
      - nodejs
      - npm
    state: present
  when:
    - ansible_facts['distribution'] == "Ubuntu"
- name: Install N
  npm:
    name: n
    global: yes
  tags:
    - install
    - node
- name: Install correct version of node
  shell: n 14
  tags:
    - install
    - node
