- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim
- name: Build neovim
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim
- name: Install Neovim
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/neovim"
    target: install
  become: yes
  tags:
    - install
    - neovim
- name: Install Vim-plug
  shell: curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags:
    - install
    - dotfiles
    - neovim
- name: Install vim Plugins
  shell: nvim +PlugInstall +qall +silent
  tags:
    - install
    - dotfiles
    - neovim
