- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim
- name: Build neovim
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim
- name: Install Neovim
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/neovim"
    target: install
  become: yes
  tags:
    - install
    - neovim
- name: Install vim Plugins
  shell: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
  tags:
    - install
    - dotfiles
    - neovim
