- name: Ensure .ssh directory exists.
  become: no
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key
  become: no
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Set authorized key took from file
  become: no
  authorized_key:
    user: lhernz
    state: present
    key: "{{ lookup('file', '.ssh/id_rsa.pub') }}"
  tags:
    - install
    - ssh
    - dotfiles
- name: Create .ssh if not exists
  become: no
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory
    mode: '0755'
  tags:
    - install
    - ssh
    - init
- name: Copy SSH Keys
  become: no
  ansible.builtin.copy:
    src: .ssh/id_rsa
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    mode: '0600'
    decrypt: 'yes'
  tags:
    - install
    - ssh
    - init
