- name: Install ZSH
  community.general.pacman:
    name: zsh
    state: present
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
  when:
    - ansible_facts['distribution'] == "Archlinux"
- name: Install ZSH (UBUNTU)
  apt:
    name: zsh
    state: present
  when:
    - ansible_facts['distribution'] == "Ubuntu"
- name: Change shell to zsh
  shell: /bin/zsh
  tags:
    - install
    - dotfiles
    - productivity
    - zsh
- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
