- name: Install ZSH
  apt: 
    name: zsh
    state: present
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Change shell to zsh
  shell: /bin/zsh
  tags:
    - install
    - dotfiles
    - productivity
    - zsh
- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
